### ISSUE TITLE
Still don't know hot to save the textured model

### ISSUE THREAD

**Issue by Yuanhong200727** [tijiang13/InstantAvatar#15]
Awesome work!After seeing this [issue](https://github.com/tijiang13/InstantAvatar/issues/5#:~:text=You%20can%20check%20out%20instant_avatar/utils/marching_cube.py),I still don't know how to export a textured model.Could you give me more details?Thanks!

**Comment by tijiang13** [comment]
Hi Yuanhong,

The basic idea is to extract points with a density greater than a certain threshold and query the network to obtain the corresponding color for these points. The first step can be accomplished by utilizing the provided marching cube functions.

Best,
Tianjian

**Comment by Yuanhong200727** [comment]
Thank you sir,I will try.But when I run `bash scripts/custom/process-sequence.sh ./data/custom/seattle neutral`,something was wrong.And here is the Traceback:
`Running OpenPose in /home/lingjing/Downloads/项目资源/github/InstantAvatar/data/custom/seattle/images
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
OpenPose demo successfully finished. Total time: 1.533087 seconds.
Running mask in /home/lingjing/Downloads/项目资源/github/InstantAvatar/data/custom/seattle
Using ROMP v1
  0%|                                                    | 0/41 [00:00<?, ?it/s]ROMP 'forward' executed in 1.1861s, FPS 0.8
  2%|█                                           | 1/41 [00:01<00:48,  1.20s/it]ROMP 'forward' executed in 0.0474s, FPS 21.1
ROMP 'forward' executed in 0.0474s, FPS 21.1
  7%|███▏                                        | 3/41 [00:01<00:13,  2.77it/s]ROMP 'forward' executed in 0.0465s, FPS 21.5
ROMP 'forward' executed in 0.0461s, FPS 21.7
 12%|█████▎                                      | 5/41 [00:01<00:07,  4.80it/s]ROMP 'forward' executed in 0.0467s, FPS 21.4
ROMP 'forward' executed in 0.0465s, FPS 21.5
 17%|███████▌                                    | 7/41 [00:01<00:05,  6.78it/s]ROMP 'forward' executed in 0.0466s, FPS 21.5
ROMP 'forward' executed in 0.0478s, FPS 20.9
 22%|█████████▋                                  | 9/41 [00:01<00:03,  8.60it/s]ROMP 'forward' executed in 0.0472s, FPS 21.2
ROMP 'forward' executed in 0.0464s, FPS 21.6
 27%|███████████▌                               | 11/41 [00:01<00:02, 10.24it/s]ROMP 'forward' executed in 0.0896s, FPS 11.2
ROMP 'forward' executed in 0.0470s, FPS 21.3
 32%|█████████████▋                             | 13/41 [00:02<00:02, 10.72it/s]ROMP 'forward' executed in 0.0466s, FPS 21.5
ROMP 'forward' executed in 0.0464s, FPS 21.6
 37%|███████████████▋                           | 15/41 [00:02<00:02, 11.98it/s]ROMP 'forward' executed in 0.0466s, FPS 21.5
ROMP 'forward' executed in 0.0463s, FPS 21.6
 41%|█████████████████▊                         | 17/41 [00:02<00:01, 12.97it/s]ROMP 'forward' executed in 0.0465s, FPS 21.5
ROMP 'forward' executed in 0.0467s, FPS 21.4
 46%|███████████████████▉                       | 19/41 [00:02<00:01, 13.70it/s]ROMP 'forward' executed in 0.0464s, FPS 21.6
ROMP 'forward' executed in 0.0464s, FPS 21.5
 51%|██████████████████████                     | 21/41 [00:02<00:01, 14.24it/s]ROMP 'forward' executed in 0.0468s, FPS 21.4
ROMP 'forward' executed in 0.0466s, FPS 21.4
 56%|████████████████████████                   | 23/41 [00:02<00:01, 14.63it/s]ROMP 'forward' executed in 0.0465s, FPS 21.5
ROMP 'forward' executed in 0.0467s, FPS 21.4
 61%|██████████████████████████▏                | 25/41 [00:02<00:01, 14.91it/s]ROMP 'forward' executed in 0.0468s, FPS 21.4
ROMP 'forward' executed in 0.0468s, FPS 21.4
 66%|████████████████████████████▎              | 27/41 [00:02<00:00, 15.13it/s]ROMP 'forward' executed in 0.0916s, FPS 10.9
ROMP 'forward' executed in 0.0470s, FPS 21.3
 71%|██████████████████████████████▍            | 29/41 [00:03<00:00, 13.90it/s]ROMP 'forward' executed in 0.0469s, FPS 21.3
ROMP 'forward' executed in 0.0469s, FPS 21.3
 76%|████████████████████████████████▌          | 31/41 [00:03<00:00, 14.43it/s]ROMP 'forward' executed in 0.0467s, FPS 21.4
ROMP 'forward' executed in 0.0476s, FPS 21.0
 80%|██████████████████████████████████▌        | 33/41 [00:03<00:00, 14.76it/s]ROMP 'forward' executed in 0.0476s, FPS 21.0
ROMP 'forward' executed in 0.0476s, FPS 21.0
 85%|████████████████████████████████████▋      | 35/41 [00:03<00:00, 14.96it/s]ROMP 'forward' executed in 0.0475s, FPS 21.1
ROMP 'forward' executed in 0.0475s, FPS 21.1
 90%|██████████████████████████████████████▊    | 37/41 [00:03<00:00, 15.05it/s]ROMP 'forward' executed in 0.0477s, FPS 21.0
ROMP 'forward' executed in 0.0489s, FPS 20.5
 95%|████████████████████████████████████████▉  | 39/41 [00:03<00:00, 15.07it/s]ROMP 'forward' executed in 0.0470s, FPS 21.3
ROMP 'forward' executed in 0.0472s, FPS 21.2
100%|███████████████████████████████████████████| 41/41 [00:03<00:00, 10.62it/s]
Refining SMPL...
WARNING: You are using a SMPL model, with only 10 shape coefficients.
100%|████████████████████████| 500/500 [00:03<00:00, 154.39it/s, loss: 3.326783]
Traceback (most recent call last):
  File "scripts/visualize-SMPL.py", line 123, in <module>
    smpl_seq = SMPLSequence(poses_body=smpl_params["body_pose"],
  File "/home/lingjing/Downloads/项目资源/github/InstantAvatar/env/lib/python3.8/site-packages/aitviewer/renderables/smpl.py", line 161, in __init__
    self.vertices, self.joints, self.faces, self.skeleton = self.fk()
  File "/home/lingjing/Downloads/项目资源/github/InstantAvatar/env/lib/python3.8/site-packages/aitviewer/renderables/smpl.py", line 415, in fk
    verts, joints = self.smpl_layer(
  File "/home/lingjing/Downloads/项目资源/github/InstantAvatar/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lingjing/Downloads/项目资源/github/InstantAvatar/env/lib/python3.8/site-packages/aitviewer/models/smpl.py", line 258, in forward
    return self.fk(*args, **kwargs)
  File "/home/lingjing/Downloads/项目资源/github/InstantAvatar/env/lib/python3.8/site-packages/aitviewer/models/smpl.py", line 186, in fk
    assert poses_body.shape[1] == self.bm.NUM_BODY_JOINTS * 3
AssertionError`
How could this happen?

**Comment by tijiang13** [comment]
That's weird. What's the shape of `smpl_params["body_pose"]`?

**Comment by Yuanhong200727** [comment]
[my_data.txt](https://github.com/tijiang13/InstantAvatar/files/11519472/my_data.txt)
Here is `smpl_params["body_pose"]`,which was save in my_data.txt.It's a numpy array[41][69].

**Comment by tijiang13** [comment]
> [my_data.txt](https://github.com/tijiang13/InstantAvatar/files/11519472/my_data.txt)
> Here is `smpl_params["body_pose"]`,which was save in my_data.txt.It's a numpy array[41][69].

Ok, (41, 69) is the correct shape (SMPL has 23 * 3) pose parameters.

But then what is the `self.bm.NUM_BODY_JOINTS`?

**Comment by Yuanhong200727** [comment]
Oh!I print it and it was 21

**Comment by tijiang13** [comment]
As can be seen here: https://github.com/vchoutas/smplx/blob/main/smplx/body_models.py#L48 if the SMPL class is created correctly then it should have 23 joints.

**Comment by tijiang13** [comment]
Btw I forgot to mention that the quality of mesh extracted from a NeRF-based model is usually not ideal and ours is no exception. If the textured mesh is really what you need I'd suggest trying https://github.com/MoyGcc/vid2avatar instead.

Best, Tianjian

**Comment by Yuanhong200727** [comment]
Thanks,sir,having sloved the problem.The reason was that I wrongly set the smplx_models path without checking for [this](https://github.com/vchoutas/smplx#:~:text=You%20can%20either%20use%20the%20create%20function%20from%20body_models%20or%20directly%20call%20the%20constructor%20for%20the%20SMPL%2C%20SMPL%2BH%20and%20SMPL%2DX%20model.%20The%20path%20to%20the%20model%20can%20either%20be%20the%20path%20to%20the%20file%20with%20the%20parameters%20or%20a%20directory%20with%20the%20following%20structure%3A)
