### ISSUE TITLE
Error about animate.py

### ISSUE THREAD

**Issue by mch0dmin** [tijiang13/InstantAvatar#17]
**Env :** 
Ubuntu18.04
NVIDIA2080Ti
CUDA11.6

```
$ HYDRA_FULL_ERROR=1 bash ./bash/run-demo.sh
Global seed set to 42
Switch to /home/miaochex/mlab/m20230522142823_instantavatar/m20230522142855_instantavatar_base/InstantAvatar/outputs/peoplesnapshot/demo/male-3-casual
[train] Loading from /home/miaochex/mlab/m20230522142823_instantavatar/m20230522142855_instantavatar_base/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_train.npz
[val] Loading from /home/miaochex/mlab/m20230522142823_instantavatar/m20230522142855_instantavatar_base/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_val.npz
[test] Loading from /home/miaochex/mlab/m20230522142823_instantavatar/m20230522142855_instantavatar_base/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_test.npz
[2023-05-23 12:11:59,186][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmpks1bxmcn
[2023-05-23 12:11:59,187][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmpks1bxmcn/_remote_module_non_scriptable.py
/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to /home/miaochex/.cache/torch/hub/checkpoints/alexnet-owt-7be5be79.pth
100%|██████████| 233M/233M [00:16<00:00, 15.0MB/s]
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name       | Type       | Params
------------------------------------------
0 | net_coarse | NeRFNGPNet | 13.0 M
1 | loss_fn    | NGPLoss    | 14.7 M
2 | evaluator  | Evaluator  | 2.5 M
------------------------------------------
13.0 M    Trainable params
17.2 M    Non-trainable params
30.2 M    Total params
120.893   Total estimated model params size (MB)
Saving configs.
Epoch 49: 100%|██████████| 115/115 [00:05<00:00, 19.94it/s, v_num=0]LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Testing: 100%|██████████| 55/55 [00:07<00:00,  7.18it/s]
Global seed set to 42
Switch to /home/miaochex/mlab/m20230522142823_instantavatar/m20230522142855_instantavatar_base/InstantAvatar/outputs/peoplesnapshot/demo/male-3-casual
[train] Loading from /home/miaochex/mlab/m20230522142823_instantavatar/m20230522142855_instantavatar_base/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_train.npz
[val] Loading from /home/miaochex/mlab/m20230522142823_instantavatar/m20230522142855_instantavatar_base/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_val.npz
[test] Loading from /home/miaochex/mlab/m20230522142823_instantavatar/m20230522142855_instantavatar_base/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_test.npz
[2023-05-23 12:17:03,266][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmpul4od4f1
[2023-05-23 12:17:03,266][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmpul4od4f1/_remote_module_non_scriptable.py
/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Resume from checkpoints/last.ckpt
/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
320it [00:34,  9.29it/s]
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Traceback (most recent call last):
  File "animate.py", line 121, in <module>
    main()
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "animate.py", line 118, in main
    imageio.mimsave(f"{folder}/{animation}.gif", imgs, fps=30)
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/imageio/v2.py", line 484, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "/home/miaochex/anaconda3/envs/m20230522144544_instantavatar/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 354, in write
    raise TypeError(
TypeError: The keyword `fps` is no longer supported. Use `duration`(in ms) instead, e.g. `fps=50` == `duration=20` (1000 * 1/50).
```

the result of `pip list`  as follows:

```
Package                 Version
----------------------- ------------------
absl-py                 1.4.0
aiohttp                 3.8.4
aiosignal               1.3.1
antlr4-python3-runtime  4.8
async-timeout           4.0.2
attrs                   23.1.0
cachetools              5.3.0
certifi                 2023.5.7
chardet                 3.0.4
charset-normalizer      3.1.0
chumpy                  0.70
colorama                0.4.6
frozenlist              1.3.3
fsspec                  2023.5.0
future                  0.18.3
fvcore                  0.1.5.post20221221
google-auth             2.18.1
google-auth-oauthlib    1.0.0
grpcio                  1.55.0
h5py                    3.8.0
hydra-core              1.1.2
idna                    2.8
imageio                 2.28.1
importlib-metadata      6.6.0
importlib-resources     5.2.3
iopath                  0.1.10
joblib                  1.2.0
lpips                   0.1.4
Markdown                3.4.3
MarkupSafe              2.1.2
multidict               6.0.4
ninja                   1.11.1
numpy                   1.23.0
oauthlib                3.0.0
omegaconf               2.1.2
opencv-python           4.7.0.72
packaging               23.1
pandas                  2.0.1
Pillow                  9.5.0
pip                     23.0.1
portalocker             2.7.0
protobuf                4.23.1
pyasn1                  0.5.0
pyasn1-modules          0.3.0
pyDeprecate             0.3.1
python-dateutil         2.8.2
pytorch-lightning       1.5.7
pytorch3d               0.7.2
pytz                    2023.3
PyYAML                  6.0
requests                2.21.0
requests-oauthlib       1.3.1
rsa                     4.9
scipy                   1.10.1
setuptools              66.0.0
six                     1.16.0
smplx                   0.1.28
tabulate                0.9.0
tensorboard             2.13.0
tensorboard-data-server 0.7.0
termcolor               2.3.0
tinycudann              1.6
torch                   1.13.1+cu116
torch-ema               0.3
torchmetrics            0.11.4
torchvision             0.14.1+cu116
tqdm                    4.65.0
typing_extensions       4.5.0
tzdata                  2023.3
urllib3                 1.24.3
Werkzeug                2.3.4
wheel                   0.38.4
yacs                    0.1.8
yarl                    1.9.2
zipp                    3.15.0
```

I think the version of Pillow is incorrect, but I don't know which version should be the correct one.

Thanks!

**Comment by mch0dmin** [comment]
```
vi animate.py +118

118     #imageio.mimsave(f"{folder}/{animation}.gif", imgs, fps=30)

119     imageio.mimsave(f"{folder}/{animation}.gif", imgs, duration=30)
```

it works fine.

**Comment by mch0dmin** [comment]
As mentioned above, it can work well.
