### ISSUE TITLE
module 'instant_avatar.utils' has no attribute 'loss'

### ISSUE THREAD

**Issue by dxiangkrypto** [tijiang13/InstantAvatar#27]
Hi, thank you for your awesome work! I am trying to run the demo, but I have encountered this error. Do you have any clue about this? Thank you very much in advance.

Environment: Win10
Python 3.10.9

```
 python train.py --config-name demo dataset="peoplesnapshot/male-3-casual" experiment="demo"
Global seed set to 42
Switch to C:\Users\ivc-lab-2\Students\xdw\InstantAvatar\outputs\peoplesnapshot\demo\male-3-casual
[train] Loading from C:\Users\ivc-lab-2\Students\xdw\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_train.npz
[val] Loading from C:\Users\ivc-lab-2\Students\xdw\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_val.npz
[test] Loading from C:\Users\ivc-lab-2\Students\xdw\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_test.npz
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Traceback (most recent call last):
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\utils.py", line 583, in _locate
    obj = getattr(obj, part)
AttributeError: module 'instant_avatar.utils' has no attribute 'loss'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\utils.py", line 589, in _locate
    obj = import_module(mod)
  File "C:\ProgramData\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ivc-lab-2\Students\xdw\InstantAvatar\instant_avatar\utils\loss.py", line 5, in <module>
    from third_parties.lpips import LPIPS
  File "C:\Users\ivc-lab-2\Students\xdw\InstantAvatar\third_parties\lpips\__init__.py", line 10, in <module>
    from lpips.trainer import *
ModuleNotFoundError: No module named 'lpips'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 130, in _resolve_target
    target = _locate(target)
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\utils.py", line 592, in _locate
    raise ImportError(
ImportError: Error loading 'instant_avatar.utils.loss.NGPLoss':
ModuleNotFoundError("No module named 'lpips'")
Are you sure that 'loss' is importable from module 'instant_avatar.utils'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 86, in _call_target
    return _target_(*args, **kwargs)
  File "C:\Users\ivc-lab-2\Students\xdw\InstantAvatar\instant_avatar\models\DNeRF.py", line 26, in __init__
    self.loss_fn = hydra.utils.instantiate(opt.loss)
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 218, in instantiate
    return instantiate_node(
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 321, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 135, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'instant_avatar.utils.loss.NGPLoss', see chained exception above.
full_key: opt.loss

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ivc-lab-2\Students\xdw\InstantAvatar\train.py", line 57, in <module>
    main()
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\main.py", line 48, in decorated_main
    _run_hydra(
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\utils.py", line 377, in _run_hydra
    run_and_report(
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\utils.py", line 214, in run_and_report
    raise ex
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\utils.py", line 211, in run_and_report
    return func()
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\hydra.py", line 111, in run
    _ = ret.return_value
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\core\utils.py", line 233, in return_value
    raise self._return_value
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\core\utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "C:\Users\ivc-lab-2\Students\xdw\InstantAvatar\train.py", line 32, in main
    model = hydra.utils.instantiate(opt.model, datamodule=datamodule, _recursive_=False)
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 218, in instantiate
    return instantiate_node(
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 331, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "C:\Users\ivc-lab-2\AppData\Roaming\Python\Python310\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 91, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'instant_avatar.models.DNeRF.DNeRFModel':
InstantiationException("Error locating target 'instant_avatar.utils.loss.NGPLoss', see chained exception above.\nfull_key: opt.loss")
full_key: model
```

**Comment by dxiangkrypto** [comment]
Fixed the issue after "pip instsall lpips"!

Just a bit curious, why "no module of lpips" would end up with a bug of "import error" hahaha ?
