### ISSUE TITLE
Question on preprocess my own data

### ISSUE THREAD

**Issue by hrx20000209** [tijiang13/InstantAvatar#62]
I try to preprocess my own data, which are all frames from a video, saved in `./data/custom/hrx`. I run the following command: `bash scripts/custom/process-sequence.sh ./data/custom/hrx neutral` and it shows some errors:
```
Running OpenPose in /home/msc/hrx/InstantAvatar/data/custom/hrx/images
The specified path does not exist or is not a directory.
Traceback (most recent call last):
  File "scripts/custom/run-romp.py", line 14, in <module>
    settings = romp.main.default_settings 
AttributeError: module 'romp' has no attribute 'main'
Refining SMPL...
Traceback (most recent call last):
  File "scripts/custom/refine-smpl.py", line 9, in <module>
    from pytorch3d.renderer import (
  File "/home/ntu/anaconda3/envs/instant-avatar/lib/python3.8/site-packages/pytorch3d/renderer/__init__.py", line 3, in <module>
    from .blending import (
  File "/home/ntu/anaconda3/envs/instant-avatar/lib/python3.8/site-packages/pytorch3d/renderer/blending.py", line 9, in <module>
    from pytorch3d import _C
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "scripts/visualize-SMPL.py", line 88, in <module>
    camera = dict(np.load(f"{args.path}/cameras.npz"))
  File "/home/ntu/anaconda3/envs/instant-avatar/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/msc/hrx/InstantAvatar/data/custom/hrx/cameras.npz'
```
I have created an environment by conda, then I followed the instruction to run the `install.sh`. It seems that there is some problems in the ROMP? How to solve it? I appreciate it a lot.

**Comment by tijiang13** [comment]
Hi,

You'll need to install the ROMP, as we rely on it for cameras and poses. You can refer to https://github.com/Arthur151/ROMP for the installtion.

Best, Tianjian

**Comment by hrx20000209** [comment]
> Hi,
> 
> You'll need to install the ROMP, as we rely on it for cameras and poses. You can refer to https://github.com/Arthur151/ROMP for the installtion.
> 
> Best, Tianjian

Ok! Thank you for your prompt answer. I will try it.

**Comment by NagabhushanSN24** [comment]
It would be very helpful if you can add this suggestion to README.md
