### ISSUE TITLE
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

### ISSUE THREAD

**Issue by AURORA1325** [tijiang13/InstantAvatar#7]
I sincerely thank you for your code. The problem I met as follow:

when I quickly learn and animate an avatar with bash `./bash/run-demo.sh` ，the following error is generated：
```
（instantAvatar) root@aurora:/home/InstantAvatar# bash ./bash/run-demo.sh
Global seed set to 42
Switch to /home/InstantAvatar/outputs/peoplesnapshot/demo/male-3-casual
[train] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_train.npz
[val] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_val.npz
[test] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_test.npz
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Error locating target 'instant_avatar.models.DNeRF.DNeRFModel', see chained exception above.
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Global seed set to 42
Switch to /home/InstantAvatar/outputs/peoplesnapshot/demo/male-3-casual
[train] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_train.npz
[val] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_val.npz
[test] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_test.npz
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Error locating target 'instant_avatar.models.DNeRF.DNeRFModel', see chained exception above.
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
 
my environment configuration is as follows：
- wsl ubuntu 22.04
- cuda 11.7
- python 3.10
- pytorch 1.13.1+cu116

Looking forward your reply, thank you again.

**Comment by lllianghe** [comment]
I encountered the same problem with you.

**Comment by tijiang13** [comment]
Hi,

Please run the bash with "HYDRA_FULL_ERROR=1 bash ./bash/run-demo.sh", this will display further information which will display the complete stack trace. Without which it's difficult to tell the cause.

Best,
Tianjian

**Comment by AURORA1325** [comment]
Hi，thanks for your reply.  I try to try to run the demo again with
```
HYDRA_FULL_ERROR=1 bash bash/run-demo.sh
```
and below is the erro information:
```
 root@gyj:/home/InstantAvatar# HYDRA_FULL_ERROR=1 bash ./bash/run-demo.sh
Global seed set to 42
Switch to /home/InstantAvatar/outputs/peoplesnapshot/demo/male-3-casual
[train] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_train.npz
[val] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_val.npz
[test] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_test.npz
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Traceback (most recent call last):
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 583, in _locate
    obj = getattr(obj, part)
AttributeError: module 'instant_avatar.models' has no attribute 'DNeRF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 589, in _locate
    obj = import_module(mod)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/InstantAvatar/instant_avatar/models/DNeRF.py", line 2, in <module>
    from ..deformers.smpl_deformer import SMPLDeformer
  File "/home/InstantAvatar/instant_avatar/deformers/smpl_deformer.py", line 2, in <module>
    from pytorch3d import ops
ModuleNotFoundError: No module named 'pytorch3d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 130, in _resolve_target
    target = _locate(target)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 592, in _locate
    raise ImportError(
ImportError: Error loading 'instant_avatar.models.DNeRF.DNeRFModel':
ModuleNotFoundError("No module named 'pytorch3d'")
Are you sure that 'DNeRF' is importable from module 'instant_avatar.models'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/InstantAvatar/train.py", line 53, in <module>
    main()
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/InstantAvatar/train.py", line 31, in main
    model = hydra.utils.instantiate(opt.model, datamodule=datamodule, _recursive_=False)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 218, in instantiate
    return instantiate_node(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 321, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 135, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'instant_avatar.models.DNeRF.DNeRFModel', see chained exception above.
full_key: model
Global seed set to 42
Switch to /home/InstantAvatar/outputs/peoplesnapshot/demo/male-3-casual
[train] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_train.npz
[val] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_val.npz
[test] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_test.npz
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Traceback (most recent call last):
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 583, in _locate
    obj = getattr(obj, part)
AttributeError: module 'instant_avatar.models' has no attribute 'DNeRF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 589, in _locate
    obj = import_module(mod)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/InstantAvatar/instant_avatar/models/DNeRF.py", line 2, in <module>
    from ..deformers.smpl_deformer import SMPLDeformer
  File "/home/InstantAvatar/instant_avatar/deformers/smpl_deformer.py", line 2, in <module>
    from pytorch3d import ops
ModuleNotFoundError: No module named 'pytorch3d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 130, in _resolve_target
    target = _locate(target)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 592, in _locate
    raise ImportError(
ImportError: Error loading 'instant_avatar.models.DNeRF.DNeRFModel':
ModuleNotFoundError("No module named 'pytorch3d'")
Are you sure that 'DNeRF' is importable from module 'instant_avatar.models'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/InstantAvatar/animate.py", line 121, in <module>
    main()
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/InstantAvatar/animate.py", line 88, in main
    model = hydra.utils.instantiate(opt.model, datamodule=datamodule, _recursive_=False)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 218, in instantiate
    return instantiate_node(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 321, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 135, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'instant_avatar.models.DNeRF.DNeRFModel', see chained exception above.
full_key: model
```
It seems that the erro information is come from this function named _resolve_target():
```
def _resolve_target(
    target: Union[str, type, Callable[..., Any]], full_key: str
) -> Union[type, Callable[..., Any]]:
    """Resolve target string, type or callable into type or callable."""
    if isinstance(target, str):
        try:
            target = _locate(target)
        except Exception as e:
            msg = f"Error locating target '{target}', see chained exception above."
            if full_key:
                msg += f"\nfull_key: {full_key}"
            raise InstantiationException(msg) from e
```
The erro information show that we coundn't load the ' instant_avatar.models.DNeRF.DNeRFModel'. What should I do next?

Thank you for your help, looking forward your reply.

**Comment by tijiang13** [comment]
Hi,

According to the error message, it appears that the pytorch3d package is missing:

```
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/InstantAvatar/instant_avatar/models/DNeRF.py", line 2, in <module>
    from ..deformers.smpl_deformer import SMPLDeformer
  File "/home/InstantAvatar/instant_avatar/deformers/smpl_deformer.py", line 2, in <module>
    from pytorch3d import ops
ModuleNotFoundError: No module named 'pytorch3d'
```

You can follow the install.sh to install the missing packages.

Best,
Tianjian

**Comment by AURORA1325** [comment]
Thank you for your reply. When I finish install the pytorch3d, and run it with `HYDRA_FULL_ERROR=1 bash bash/run-demo.sh`, the erro information is followed:

```
(instantAvatar) root@gyj:/home/InstantAvatar# HYDRA_FULL_ERROR=1 bash bash/run-demo.sh
Global seed set to 42
Switch to /home/InstantAvatar/outputs/peoplesnapshot/demo/male-3-casual
[train] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_train.npz
[val] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_val.npz
[test] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_test.npz
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Traceback (most recent call last):
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 583, in _locate
    obj = getattr(obj, part)
AttributeError: module 'instant_avatar.models' has no attribute 'DNeRF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 589, in _locate
    obj = import_module(mod)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/InstantAvatar/instant_avatar/models/DNeRF.py", line 2, in <module>
    from ..deformers.smpl_deformer import SMPLDeformer
  File "/home/InstantAvatar/instant_avatar/deformers/smpl_deformer.py", line 2, in <module>
    from pytorch3d import ops
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/pytorch3d/ops/__init__.py", line 7, in <module>
    from .ball_query import ball_query
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/pytorch3d/ops/ball_query.py", line 10, in <module>
    from pytorch3d import _C
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 130, in _resolve_target
    target = _locate(target)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 597, in _locate
    raise ImportError(
ImportError: Error loading 'instant_avatar.models.DNeRF.DNeRFModel':
ImportError('libc10_cuda.so: cannot open shared object file: No such file or directory')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/InstantAvatar/train.py", line 53, in <module>
    main()
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/InstantAvatar/train.py", line 31, in main
    model = hydra.utils.instantiate(opt.model, datamodule=datamodule, _recursive_=False)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 218, in instantiate
    return instantiate_node(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 321, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 135, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'instant_avatar.models.DNeRF.DNeRFModel', see chained exception above.
full_key: model
Global seed set to 42
Switch to /home/InstantAvatar/outputs/peoplesnapshot/demo/male-3-casual
[train] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_train.npz
[val] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_val.npz
[test] Loading from /home/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_test.npz
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Traceback (most recent call last):
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 583, in _locate
    obj = getattr(obj, part)
AttributeError: module 'instant_avatar.models' has no attribute 'DNeRF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 589, in _locate
    obj = import_module(mod)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/InstantAvatar/instant_avatar/models/DNeRF.py", line 2, in <module>
    from ..deformers.smpl_deformer import SMPLDeformer
  File "/home/InstantAvatar/instant_avatar/deformers/smpl_deformer.py", line 2, in <module>
    from pytorch3d import ops
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/pytorch3d/ops/__init__.py", line 7, in <module>
    from .ball_query import ball_query
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/pytorch3d/ops/ball_query.py", line 10, in <module>
    from pytorch3d import _C
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 130, in _resolve_target
    target = _locate(target)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 597, in _locate
    raise ImportError(
ImportError: Error loading 'instant_avatar.models.DNeRF.DNeRFModel':
ImportError('libc10_cuda.so: cannot open shared object file: No such file or directory')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/InstantAvatar/animate.py", line 121, in <module>
    main()
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/InstantAvatar/animate.py", line 88, in main
    model = hydra.utils.instantiate(opt.model, datamodule=datamodule, _recursive_=False)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 218, in instantiate
    return instantiate_node(
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 321, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/root/anaconda3/envs/instantAvatar/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 135, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'instant_avatar.models.DNeRF.DNeRFModel', see chained exception above.
full_key: model
```
and I try some instrution in the console:
```
(instantAvatar) root@gyj:/home/InstantAvatar# python
Python 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import pytorch3d
>>> from pytorch3d import _C
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory
>>> 
```
Thank you for your help, looking forward your reply.

**Comment by tijiang13** [comment]
Hi,

According to the error message:

```
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

Apparently it fails to run, let alone generating a checkpoint.

I'd recommend to create a clean environment, and install everything once again:

```
python -m venv env
source ./env/bin/activate
bash install.sh
```

Best,
Tianjian

**Comment by AURORA1325** [comment]
Thank you. When I create a clean environment, and install everything once again according  to the install.sh，it works. Thank you again!
