### ISSUE TITLE
the problem with hydra

### ISSUE THREAD

**Issue by lllianghe** [tijiang13/InstantAvatar#8]
Thank you for your code. But when I try to run the demo, with `bash ./bash/run-demo.sh`, I encountered some problems.
Here is the error:
`$ bash ./bash/run-demo.sh
Global seed set to 42
Switch to C:\Users\16028\Desktop\lhe_project\InstantAvatar\outputs\peoplesnapshot\demo\male-3-casual
[train] Loading from C:\Users\16028\Desktop\lhe_project\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_train.npz
[val] Loading from C:\Users\16028\Desktop\lhe_project\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_val.npz
[test] Loading from C:\Users\16028\Desktop\lhe_project\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_test.npz
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Error locating target 'instant_avatar.models.DNeRF.DNeRFModel', see chained exception above.
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Global seed set to 42
Switch to C:\Users\16028\Desktop\lhe_project\InstantAvatar\outputs\peoplesnapshot\demo\male-3-casual
[train] Loading from C:\Users\16028\Desktop\lhe_project\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_train.npz
[val] Loading from C:\Users\16028\Desktop\lhe_project\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_val.npz
[test] Loading from C:\Users\16028\Desktop\lhe_project\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_test.npz
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Error locating target 'instant_avatar.models.DNeRF.DNeRFModel', see chained exception above.
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
`
After debugging, I think there is a problem with the code on line 31 of train.py :`datamodule = hydra.utils.instantiate(opt.dataset, _recursive_=False)`

Looking forward to you reply, thank you.

**Comment by tijiang13** [comment]
Hi,

Please run the bash with "HYDRA_FULL_ERROR=1 bash ./bash/run-demo.sh", this will display further information which will display the complete stack trace. Without which it's difficult to tell the cause.

Best,
Tianjian

**Comment by lllianghe** [comment]
> Hi,
> 
> Please run the bash with "HYDRA_FULL_ERROR=1 bash ./bash/run-demo.sh", this will display further information which will display the complete stack trace. Without which it's difficult to tell the cause.
> 
> Best, Tianjian

Here is the complete stack trace:

$ HYDRA_FULL_ERROR=1 bash ./bash/run-demo.sh
Global seed set to 42
Switch to C:\Users\16028\Desktop\lhe_project\InstantAvatar\outputs\peoplesnapshot\demo\male-3-casual
[train] Loading from C:\Users\16028\Desktop\lhe_project\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_train.npz
[val] Loading from C:\Users\16028\Desktop\lhe_project\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_val.npz
[test] Loading from C:\Users\16028\Desktop\lhe_project\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_test.npz
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Traceback (most recent call last):
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\utils.py", line 583, in _locate
    obj = getattr(obj, part)
AttributeError: module 'instant_avatar.models' has no attribute 'DNeRF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\utils.py", line 589, in _locate
    obj = import_module(mod)
  File "C:\Users\16028\anaconda3\envs\3d\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\16028\Desktop\lhe_project\InstantAvatar\instant_avatar\models\DNeRF.py", line 2, in <module>
    from ..deformers.smpl_deformer import SMPLDeformer
  File "C:\Users\16028\Desktop\lhe_project\InstantAvatar\instant_avatar\deformers\smpl_deformer.py", line 2, in <module>
    from pytorch3d import ops
ModuleNotFoundError: No module named 'pytorch3d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 130, in _resolve_target
    target = _locate(target)
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\utils.py", line 592, in _locate
    raise ImportError(
ImportError: Error loading 'instant_avatar.models.DNeRF.DNeRFModel':
ModuleNotFoundError("No module named 'pytorch3d'")
Are you sure that 'DNeRF' is importable from module 'instant_avatar.models'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\16028\Desktop\lhe_project\InstantAvatar\train.py", line 48, in <module>
    main()
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\main.py", line 48, in decorated_main
    _run_hydra(
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\utils.py", line 377, in _run_hydra
    run_and_report(
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\utils.py", line 214, in run_and_report
    raise ex
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\utils.py", line 211, in run_and_report
    return func()
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\hydra.py", line 111, in run
    _ = ret.return_value
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\core\utils.py", line 233, in return_value
    raise self._return_value
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\core\utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "C:\Users\16028\Desktop\lhe_project\InstantAvatar\train.py", line 27, in main
    model = hydra.utils.instantiate(opt.model, datamodule=datamodule, _recursive_=False)
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 218, in instantiate
    return instantiate_node(
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 321, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 135, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'instant_avatar.models.DNeRF.DNeRFModel', see chained exception above.
full_key: model
Global seed set to 42
Switch to C:\Users\16028\Desktop\lhe_project\InstantAvatar\outputs\peoplesnapshot\demo\male-3-casual
[train] Loading from C:\Users\16028\Desktop\lhe_project\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_train.npz
[val] Loading from C:\Users\16028\Desktop\lhe_project\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_val.npz
[test] Loading from C:\Users\16028\Desktop\lhe_project\InstantAvatar\data\PeopleSnapshot\male-3-casual\poses\anim_nerf_test.npz
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Traceback (most recent call last):
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\utils.py", line 583, in _locate
    obj = getattr(obj, part)
AttributeError: module 'instant_avatar.models' has no attribute 'DNeRF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\utils.py", line 589, in _locate
    obj = import_module(mod)
  File "C:\Users\16028\anaconda3\envs\3d\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\16028\Desktop\lhe_project\InstantAvatar\instant_avatar\models\DNeRF.py", line 2, in <module>
    from ..deformers.smpl_deformer import SMPLDeformer
  File "C:\Users\16028\Desktop\lhe_project\InstantAvatar\instant_avatar\deformers\smpl_deformer.py", line 2, in <module>
    from pytorch3d import ops
ModuleNotFoundError: No module named 'pytorch3d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 130, in _resolve_target
    target = _locate(target)
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\utils.py", line 592, in _locate
    raise ImportError(
ImportError: Error loading 'instant_avatar.models.DNeRF.DNeRFModel':
ModuleNotFoundError("No module named 'pytorch3d'")
Are you sure that 'DNeRF' is importable from module 'instant_avatar.models'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\16028\Desktop\lhe_project\InstantAvatar\animate.py", line 121, in <module>
    main()
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\main.py", line 48, in decorated_main
    _run_hydra(
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\utils.py", line 377, in _run_hydra
    run_and_report(
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\utils.py", line 214, in run_and_report
    raise ex
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\utils.py", line 211, in run_and_report
    return func()
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\hydra.py", line 111, in run
    _ = ret.return_value
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\core\utils.py", line 233, in return_value
    raise self._return_value
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\core\utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "C:\Users\16028\Desktop\lhe_project\InstantAvatar\animate.py", line 88, in main
    model = hydra.utils.instantiate(opt.model, datamodule=datamodule, _recursive_=False)
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 218, in instantiate
    return instantiate_node(
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 321, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "C:\Users\16028\anaconda3\envs\3d\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 135, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'instant_avatar.models.DNeRF.DNeRFModel', see chained exception above.
full_key: model

**Comment by tijiang13** [comment]
Hi,

According to the error message, it appears that the pytorch3d package is missing. You can follow the install.sh to install the missing packages.


Best,
Tianjian

**Comment by TharHtetAungg** [comment]
Hi , how did you solve it ? In my case, I think it is not Pytorch3d. 

```
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    main()
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 88, in run
    cfg = self.compose_config(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 559, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 141, in load_configuration
    return self._load_configuration_impl(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 239, in _load_configuration_impl
    defaults_list = create_defaults_list(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 748, in create_defaults_list
    defaults, tree = _create_defaults_list(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 718, in _create_defaults_list
    defaults_tree = _create_defaults_tree(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 356, in _create_defaults_tree
    ret = _create_defaults_tree_impl(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 455, in _create_defaults_tree_impl
    return _expand_virtual_root(repo, root, overrides, skip_missing)
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 280, in _expand_virtual_root
    subtree = _create_defaults_tree_impl(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 575, in _create_defaults_tree_impl
    add_child(children, new_root)
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 518, in add_child
    subtree_ = _create_defaults_tree_impl(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 486, in _create_defaults_tree_impl
    config_not_found_error(repo=repo, tree=root)
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 802, in config_not_found_error
    raise MissingConfigException(
hydra.errors.MissingConfigException: In 'SNARF_NGP': Could not find 'dataset/'

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///mnt/c/Users/ADMIN/Desktop/InstantAvatar/confs
        provider=schema, path=structured://
Global seed set to 42
Switch to /mnt/c/Users/ADMIN/Desktop/InstantAvatar/outputs/peoplesnapshot/demo/male-3-casual
[train] Loading from /mnt/c/Users/ADMIN/Desktop/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_train.npz
[val] Loading from /mnt/c/Users/ADMIN/Desktop/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_val.npz
[test] Loading from /mnt/c/Users/ADMIN/Desktop/InstantAvatar/data/PeopleSnapshot/male-3-casual/poses/anim_nerf_test.npz
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual', 'experiment=demo']
Traceback (most recent call last):
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/utils.py", line 583, in _locate
    obj = getattr(obj, part)
AttributeError: module 'instant_avatar.models' has no attribute 'DNeRF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/utils.py", line 589, in _locate
    obj = import_module(mod)
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/ADMIN/Desktop/InstantAvatar/instant_avatar/models/DNeRF.py", line 2, in <module>
    from ..deformers.smpl_deformer import SMPLDeformer
  File "/mnt/c/Users/ADMIN/Desktop/InstantAvatar/instant_avatar/deformers/smpl_deformer.py", line 1, in <module>
    from third_parties.pytorch3d import ops
  File "/mnt/c/Users/ADMIN/Desktop/InstantAvatar/third_parties/pytorch3d/__init__.py", line 1, in <module>
    from . import ops
  File "/mnt/c/Users/ADMIN/Desktop/InstantAvatar/third_parties/pytorch3d/ops.py", line 20, in <module>
    _C = load(name='knn',
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1623, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'knn': [1/1] c++ knn.o knn.cuda.o knn_cpu.o -shared -L/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/home/thar/miniconda3/envs/instant/lib64 -lcudart -o knn.so
FAILED: knn.so
c++ knn.o knn.cuda.o knn_cpu.o -shared -L/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/home/thar/miniconda3/envs/instant/lib64 -lcudart -o knn.so
/usr/bin/ld: cannot find -lcudart: No such file or directory
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 130, in _resolve_target
    target = _locate(target)
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/utils.py", line 597, in _locate
    raise ImportError(
ImportError: Error loading 'instant_avatar.models.DNeRF.DNeRFModel':
RuntimeError("Error building extension 'knn': [1/1] c++ knn.o knn.cuda.o knn_cpu.o -shared -L/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/home/thar/miniconda3/envs/instant/lib64 -lcudart -o knn.so\nFAILED: knn.so \nc++ knn.o knn.cuda.o knn_cpu.o -shared -L/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/home/thar/miniconda3/envs/instant/lib64 -lcudart -o knn.so\n/usr/bin/ld: cannot find -lcudart: No such file or directory\ncollect2: error: ld returned 1 exit status\nninja: build stopped: subcommand failed.\n")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "animate.py", line 121, in <module>
    main()
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "animate.py", line 88, in main
    model = hydra.utils.instantiate(opt.model, datamodule=datamodule, _recursive_=False)
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 218, in instantiate
    return instantiate_node(
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 321, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/thar/miniconda3/envs/instant/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 135, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'instant_avatar.models.DNeRF.DNeRFModel', see chained exception above.
full_key: model
```
